name: screen_record_plus
description: "Native screen recording with coordinate-based capture for Android and iOS."
version: 1.1.0
repository: https://github.com/BrianTran24/screen_record
homepage: https://pub.dev/publishers/brian98.com/packages

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  path: ^1.9.0
  ffmpeg_kit_flutter:
   git:
      url: https://github.com/Sahad2701/ffmpeg-kit.git
      ref: flutter_fix_retired_v6.0.3
      path: flutter/flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.screen_record_plus
        pluginClass: ScreenRecordPlusPlugin
      ios:
        pluginClass: ScreenRecordPlusPlugin
